### ISSUE TITLE
Implement waveform-summing methods and scripts

### ISSUE THREAD

**Issue by allan-ylsung** [darkside-princeton/sipm-analysis#7]
Rewrite script/root_spewf.py and script/root_triplet.py in object-oriented style.

1. Create scripts under `sipm/recon/` and modify class methods under `sipm/io/` to do the same tasks done with the previous two python scripts. 
2. In the case of laser data, select single PE waveform according to the filtered amplitude range provided in the calibration file.
3. In the case of scintillation data, take Fprompt range and minimum energy as input for waveform selection.
In both cases, calibration result file needs to be specified.

**Comment by akojamil** [comment]
Summing of channels is already partially implemented in here: https://github.com/darkside-princeton/sipm-analysis/blob/main/sipm/io/dataset.py

But this is very crude and should be refined as you suggest with more flexibility.
